tokenizer:
  model_name: cssupport/t5-small-awesome-text-to-sql
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True

reward_fn:
  id: "sqli_nlp_iter"
  args:
    url: "https://k0ahsdpgv5.execute-api.us-east-1.amazonaws.com/F5/test?user="

datapool:
  id: "sqli_dataset_iterative"
  args:
    dataset: 'dataset/first_dataset_base_metrics.csv'

env:
  n_envs: 1
  args:
    max_prompt_length: 256
    max_episode_length: 256
    terminate_on_eos: True

alg:
  id: nlpo
  args:
    n_steps: 1024
    batch_size: 8
    verbose: 1
    learning_rate: 0.000001
    n_epochs: 1

  kl_div:
    coeff: 0.2
    target_kl: 0.5
  policy:
    id: maskable_seq2seq_lm_actor_critic_policy
    args:
      model_name: cssupport/t5-small-awesome-text-to-sql
      apply_model_parallel: True
      top_mask: 0.9
      min_tokens_to_keep: 100
      mask_type: 'learned_top_p'
      target_update_iterations: 16
      generation_kwargs:
        do_sample: True
        top_k: 20
        min_length: 10
        max_new_tokens: 256

train_evaluation:
  eval_batch_size: 16
  n_iters: 16
  eval_every: 16
  save_every: 8
  metrics:
    - id: sqli_detection_evasion_acc
      args: {
        url: "https://k0ahsdpgv5.execute-api.us-east-1.amazonaws.com/F5/test?user="
      }
  generation_kwargs:
    do_sample: True
    top_k: 20
    min_length: 10
    max_new_tokens: 256