tokenizer:
  model_name: cssupport/t5-small-awesome-text-to-sql
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: true

reward_fn:
  id: sqli_nlp_iter

datapool:
  id: sqli_dataset_iterative
  args:
    dataset: dataset/training_dataset.csv

env:
  n_envs: 1
  args:
    max_prompt_length: 256
    max_episode_length: 256
    terminate_on_eos: true

alg:
  id: nlpo
  args:
    n_steps: 1024
    batch_size: 8
    verbose: 1
    learning_rate: 0.000001
    n_epochs: 2

  kl_div:
    coeff: 0.2
    target_kl: 0.5
  policy:
    id: maskable_seq2seq_lm_actor_critic_policy
    args:
      model_name: /home/neptune/capstone_project/project/trained_model/model_iter_4
      apply_model_parallel: true
      top_mask: 0.9
      min_tokens_to_keep: 100
      mask_type: learned_top_p
      target_update_iterations: 16
      generation_kwargs:
        do_sample: true
        top_k: 20
        min_length: 10
        max_new_tokens: 256

train_evaluation:
  eval_batch_size: 8
  n_iters: 8
  eval_every: 2
  save_every: 2
  metrics:
  - id: sqli_detection_evasion_acc
  generation_kwargs:
    do_sample: true
    top_k: 20
    min_length: 10
    max_new_tokens: 256
